### ISSUE TITLE
I2C error using Python 3.11.2

### ISSUE THREAD

**Issue by lauriaclarke** [adafruit/CircuitPython_NAU7802#16]
I keep getting the following error using the NAU7802 with this library on RPi 5 and Python 3.11.2. This error occurs on killing the [simple test](https://github.com/adafruit/CircuitPython_NAU7802/blob/main/examples/nau7802_simpletest.py) in the examples directory. When I extend this code for my own application the same error occurs each time the ```__pu_cycle_ready``` bits are read during a call to ```nau7803.available```.

```
Traceback (most recent call last):
  File "/home/pi/Documents/unfinished arch/nau_test.py", line 66, in <module>
    value = read_raw_value()
            ^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/unfinished arch/nau_test.py", line 39, in read_raw_value
    while not nau7802.available():
              ^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/unfinished arch/lib/python3.11/site-packages/cedargrove_nau7802.py", line 297, in available
    return self._pu_cycle_ready
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/unfinished arch/lib/python3.11/site-packages/adafruit_register/i2c_bit.py", line 59, in __get__
    i2c.write_then_readinto(self.buffer, self.buffer, out_end=1, in_start=1)
  File "/home/pi/Documents/unfinished arch/lib/python3.11/site-packages/adafruit_bus_device/i2c_device.py", line 140, in write_then_readinto
    self.i2c.writeto_then_readfrom(
  File "/home/pi/Documents/unfinished arch/lib/python3.11/site-packages/busio.py", line 224, in writeto_then_readfrom
    return self._i2c.writeto_then_readfrom(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/unfinished arch/lib/python3.11/site-packages/adafruit_blinka/microcontroller/generic_linux/i2c.py", line 98, in writeto_then_readfrom
    readin = self._i2c_bus.read_i2c_block_data(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/unfinished arch/lib/python3.11/site-packages/Adafruit_PureIO/smbus.py", line 264, in read_i2c_block_data
    ioctl(self._device.fileno(), I2C_RDWR, request)
KeyboardInterrupt
```

**Comment by makermelissa** [comment]
I was able to reproduce the error. I first ran the example using CircuitPython to see what to expect when it works. I noticed in addition to the above error, the values are coming back fairly random and not being affected by putting pressure on the load cell.

**Comment by makermelissa** [comment]
Ok, [enabling clock stretching](https://learn.adafruit.com/circuitpython-on-raspberrypi-linux/i2c-clock-stretching) fixed the random values. To stop the error from showing, you could put it in a try/except block checking for a KeyboardInterrupt exception with a pass on the except.

So something like:
```
try:
    value = read_raw_value()
except KeyboardInterrupt:
    pass
```

**Comment by makermelissa** [comment]
Closing as there's not much more I can do on this.
